env:
  CIRRUS_CLONE_DEPTH: "20"
  CIRRUS_SHELL: bash
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]

eks_container: &CONTAINER_DEFINITION
  image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-g7-latest
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default

build_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 8
    memory: 4G
  env:
    # Possible values for ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa, sonarsource-public-qa
    ARTIFACTORY_DEPLOY_REPO: FIXME
    ARTIFACTORY_DEPLOY_USERNAME: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer username]
    ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
    DEPLOY_PULL_REQUEST: "true"
  build_script:
    - source cirrus-env BUILD-PRIVATE
    - ./gradlew build

qa_task:
  depends_on:
    - build
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 8
    memory: 8G
  env:
    # Possible values for ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa, sonarsource-public-qa
    ARTIFACTORY_DEPLOY_REPO: FIXME
    ARTIFACTORY_DEPLOY_USERNAME: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer username]
    ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
    DEPLOY_PULL_REQUEST: "true"
  build_script:
    - ./gradlew build --exclude-task test
  its_script:
    - source cirrus-env BUILD-PRIVATE
    - git submodule update --init its/sources
    - ./gradlew build --project-prop its --info --stacktrace --console=plain --build-cache --no-daemon "-Dorchestrator.configUrl=file:///$CIRRUS_WORKING_DIR/orchestrator.properties" "-Dorchestrator.artifactory.accessToken=${ARTIFACTORY_ACCESS_TOKEN}"

promote_task:
  depends_on:
    - build
    - qa
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 1
    memory: 1G
  env:
    ARTIFACTORY_PROMOTE_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
    ARTIFACTS: FIXME # This was for Burgr links, is it still required?
  promote_script:
    - echo "You are good to go!"
