name: Update Rule Metadata

on: workflow_dispatch

jobs:
  update-rule-metadata:
    runs-on: warp-custom-ubuntu-24-04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Update Rule Metadata
        id: update-rule-metadata
        uses: SonarSource/release-github-actions/update-rule-metadata@v1
        with:
          labels: ''
          rspec-token-suffix: 'rspec'
